Don't pass snapshot to IMagicFileSystem.
LeastAuthority/magic-folder pull request #514
Opened 2021-07-28 17:51 UTC by tomprince

@meejah This is the followup to #500 that we discussed.

- Don't pass snapshot to IMagicFileSystem.
- Remove .name from RemoteSnapshot.

Once #500 lands, I'll re-target this to main, but for the moment, it is against the current (as of this PR being opened) state of #500.

2021-08-08 02:46 UTC, meejah requested changes
This (along with 500) definitely gets us _closer_ to solving the issues with this refactoring that we chatted about.

However, the problem that "name" now refers to relpath sometimes and mangled-name some other times is still worsened by these PRs (e.g. the database column is still "name" but got re-used as relpath, and some other inline comments to this effect).

To re-iterate from the conversation you mention: whether things internally use mangled-name or relpath is rather arbitrary -- but they _absolutely should be consistent_ and so I don't want to get stuck in a half-way position where there's both (since it's already confusing enough). Up until now, the arbitrary decision is that "name means mangled-name" and so we can't just start using "name means relpath, but only here and over there" .. we should use "relpath" to mean relative path and "name" (or "manged_name") to mean the other thing. Also from that conversation is that this may have implications on the signature spec as well (although also maybe not); has that been analyzed?

2021-08-08 03:21 UTC, tomprince commented
> However, the problem that "name" now refers to relpath sometimes and mangled-name some other times is still worsened by these PRs (e.g. the database column is still "name" but got re-used as relpath, and some other inline comments to this effect).

I've not looked at any magic-folder code for close to a week, but where do we ever (after these two PRs) use `name` to refer to the mangled name? As far as I can tell, the only place the mangled form is given a name after this is `encoded_relpath_u` in `_CollectiveDirnodeParticipant.files`. I'll admit that relpath and name are used interchangably, which can be confusing but not ambiguous.

2021-08-09 17:03 UTC, tomprince commented
> However, the problem that "name" now refers to relpath sometimes and mangled-name some other times is still worsened by these PRs (e.g. the database column is still "name" but got re-used as relpath, and some other inline comments to this effect).

As I mentioned above, `name` is never used for the mangled name. I have gone and fixed up the comments that suggest it is a mangled name (which I'll push shortly). I'd be happy to go through and change all references from name to relpath, but I'd prefer to do that in a followup PR.

> To re-iterate from the conversation you mention: whether things internally use mangled-name or relpath is rather arbitrary 

Yes and no. Certainly we can use whatever for internally we want, we could even use something else like the base64 encoded version or a rot13[1] encoded version. However, given that relpath isn't something arbitrary (unlike the mangling we've chosen), picking that form as the one we use internally isn't entirely arbitrary.

> but they absolutely should be consistent and so I don't want to get stuck in a half-way position where there's both

I don't think this leaves us in a half-way position (nor does #500 on its own), except for a few out-of-date comments, which I'll fix.

> Up until now, the arbitrary decision is that "name means mangled-name"

I do keep finding indications in old documentation that that *wasn't* always the case. For example https://github.com/LeastAuthority/magic-folder/blob/main/docs/snapshots.rst#signature-details talks (implicitly, by mentioning a mangled version of it) about the name being the unmangled version.

> we should use "relpath" to mean relative path and "name" (or "manged_name") to mean the other thing.

After this, we use `relpath` and `name` interchangeably to refer to the relative path and don't refer to the mangled name at all.

> Also from that conversation is that this may have implications on the signature spec as well (although also maybe not); has that been analyzed?

Reading https://github.com/LeastAuthority/magic-folder/blob/main/docs/snapshots.rst#signature-details suggests that the signature spec envisioned using the unmangled name already; it seems these two PRs bring the code (closer) in-line with the signature spec[2].

---

I'd be happy to make the changes you suggested about `s/name/relpath` if that gets #500 and this landed, though as I mentioned it isn't ambiguous.


[1] though what that means for full utf-8 name could be debated :wink: 
[2] though the spec does seem want us to use the name from the DMD to verify, rather than the embedded name which is what we currently do. Our code isn't currently structured that we have access to the DMD name at the point we verify the signature.

2021-08-09 18:14 UTC, meejah commented
> After this, we use relpath and name interchangeably to refer to the relative path and don't refer to the mangled name at all.

yes, this is the problem. I think we should be clear and use `relpath` for everything that's a relative path (including the database columns, arg names, etc). "name" was never a great label anyway, and makes even less sense if it's actually a relative-path and not an arbitrary label (as the generic "name" at least implies).

2021-08-09 20:51 UTC, tomprince commented
> > After this, we use relpath and name interchangeably to refer to the relative path and don't refer to the mangled name at all.
> 
> yes, this is the problem. I think we should be clear and use `relpath` for everything that's a relative path (including the database columns, arg names, etc). "name" was never a great label anyway, and makes even less sense if it's actually a relative-path and not an arbitrary label (as the generic "name" at least implies).

I agree we should change this. Is doing it now a blocker? (I'm partly reluctant to do it here, as I suspect it might lead to a lot of code conflicts).

2021-08-10 00:19 UTC, meejah commented
> I agree we should change this. Is doing it now a blocker? (I'm partly reluctant to do it here, as I suspect it might lead to a lot of code conflicts).

Yes, because re-using "name" to mean "relpath" (sometimes) is confusing.

I don't see that any of this re-factoring is necessary for the real feature .. but as I said, it's hard to tell because this is _just_ the refactoring, and not the real feature.

2021-08-10 18:16 UTC, tomprince commented
> I don't see that any of this re-factoring is necessary for the real feature .. but as I said, it's hard to tell because this is _just_ the refactoring, and not the real feature.

Generally no refactoring is necessary. I do tend to split work up into "making the change easy" and then "making the easy change", even if it ends up being more work than just making the change. However, my experience is that the extra work starts paying itself off fairly quickly. I also enjoy refactoring and code gardening, so am probably more aggressive about refactoring than might be strictly necessary; but it part of how I understand code and the changes I need to make and manage complexity.

2021-08-10 19:10 UTC, tomprince commented
I've gone and changed everything (except the db and the snapshot metadata) to use relpath.

2021-08-10 19:54 UTC, merged